### ISSUE TITLE
updatedAt not updated when i do some updated to document

### ISSUE THREAD

**Issue by hengkiardo** [drudge/mongoose-timestamp#13]
when i do update to docement, field `updatedAt` not updated with current Date time.
example my query

```
User.findByIdAndUpdate(id, { last_login: new Date() }).exec()
```

**Comment by sirrodgepodge** [comment]
any idea what was causing this (dates not updating on "update" command)?  I'm getting this too...

**Comment by GautamSulok** [comment]
Why this is closed? It is actually a huge issue developers facing right now
