### ISSUE TITLE
updatedAt not updated after findByIdAnd

### ISSUE THREAD

**Issue by gonenduk** [drudge/mongoose-timestamp#26]
Only works after save().
Was a mongoose limitation. Solved in mongoose 4. Please add support.

**Comment by michaek** [comment]
It does seem worthwhile to add middleware support for the mongoose `update` and `findOneAndUpdate` functions. http://mongoosejs.com/docs/middleware.html The open pull request #27 seems to address this, and it looks like the one failing test suite execution in CI could be spurious.

**Comment by michaek** [comment]
And in PR #28, @rfink takes the changes from #27 and leaves a working fork that you can investigate: https://github.com/rfink/mongoose-timestamp/tree/mongoose-4.0

**Comment by drudge** [comment]
Merged #27 and published to npm as 0.5.0
