### ISSUE TITLE
Global configuration/setup instead of by each model

### ISSUE THREAD

**Issue by lesterzone** [drudge/mongoose-timestamp#33]
First: Thanks!

Second: I tried to research about the ability to enabled timestamps 'globally'.
Is there a way to enable timestamps to the mongoose object?

like with promises:

```js
let mongoose = require('mongoose');

mongoose.Promise = global.Promise;
```

**Comment by kangsu-dev** [comment]
You can use mongoose.plugin()

http://mongoosejs.com/docs/api.html#index_Mongoose-plugin

**Comment by lesterzone** [comment]
Thanks @kangsu-dev 

```js
let mongoose = require('mongoose');
let timestamps = require('mongoose-timestamp');
mongoose.plugin(timestamps);
```
